### ISSUE TITLE
Validate `@id` references in Booking API context

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#402] opened 2021-11-23 15:02 UTC
Validate that `acceptedOffer` and `orderedItem` are `@id`s for requests, and objects for responses, within the Open Booking API.

Currently the validator will pass when `@id` references are used in the wrong context

---

~~Also (related) ensure that `@id` references are validated in the context of the feed.~~

~~For example this in a Slots feed currently passes the validator~~
```
            "facilityUse":{
               "@type":"FacilityUse",
               "@id":"https://localhost/ven_000229-rbt_000010",
               identifier":"ven_000229-rbt_000010"
           },
``` 
This has been split out into a separate issue https://github.com/openactive/data-model-validator/issues/408

**Comment by civsiv** [comment] 2022-05-05 10:58
The first part of this issue is fixed in the PR linked above.

**Comment by civsiv** [comment] 2022-05-05 11:21
The second part of the issue is slightly more nuanced. 

For the Slots feed, the correct implementation is 
```
"facilityUse": "https://localhost/ven_000229-rbt_000010",
```

The below example is incorrect:
```
"facilityUse":{
               "@type":"FacilityUse",
               "@id":"https://localhost/ven_000229-rbt_000010",
               "identifier":"ven_000229-rbt_000010"
            },
```

This is also the case for a ScheduledSession feed of RPDE `kind: ScheduledSession` but not RPDE `kind:ScheduledSession.SessionSeries`. Examples below:
```
// Valid
{
    "kind": "ScheduledSession",
    "data": {
        "@type": "ScheduledSession",
        "superEvent": "https://example.com/SessionSeries/1"
        ...
    },
    ...
}

// Invalid
{
    "kind": "ScheduledSession",
    "data": {
        "@type": "ScheduledSession",
        "superEvent": {
            "@type": "SessionSeries",
            "@id": "https://example.com/SessionSeries/1"
            ...
        }
        ...
    },
    ...
}

// Valid
{
    "kind": "ScheduledSession.SessionSeries",
    "data": {
        "@type": "ScheduledSession",
        "superEvent": {
            "@type": "SessionSeries",
            "@id": "https://example.com/SessionSeries/1"
            ...
        }
        ...
    },
    ...
}

```

### Validator

Therefore in order to implement @id reference validation with feed context, the rule must used the `kind` to determine what is valid, and therefore `kind` must be passed into the `.validate()` function `options` when used.

### Test Suite

To finish this task, Test Suite must pass `kind` where it validates the feeds in order to ensure that the Slots and ScheduledSession feeds are fully validated.

**Closed** 2022-07-16 00:05 UTC
